package rs.ac.metropolitan.projekat_cs330.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFF4BE48)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDEA1)
val md_theme_light_onPrimaryContainer = Color(0xFFF4BE48)
val md_theme_light_secondary = Color(0xFFF4BE48)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCE)
val md_theme_light_onSecondaryContainer = Color(0xFFF4BE48)
val md_theme_light_tertiary = Color(0xFF566500)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD8EC7B)
val md_theme_light_onTertiaryContainer = Color(0xFF181E00)
val md_theme_light_error = Color(0xFFF4BE48)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFF4BE48)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFFF4BE48)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFFF4BE48)
val md_theme_light_surfaceVariant = Color(0xFFEDE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4D4639)
val md_theme_light_outline = Color(0xFF7F7667)
val md_theme_light_inverseOnSurface = Color(0xFFFFECF0)
val md_theme_light_inverseSurface = Color(0xFFF4BE48)
val md_theme_light_inversePrimary = Color(0xFFF4BE48)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF7A5900)
val md_theme_light_outlineVariant = Color(0xFFD1C5B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFF4BE48)
val md_theme_dark_onPrimary = Color(0xFFF4BE48)
val md_theme_dark_primaryContainer = Color(0xFFF4BE48)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDEA1)
val md_theme_dark_secondary = Color(0xFFFFB59A)
val md_theme_dark_onSecondary = Color(0xFFF4BE48)
val md_theme_dark_secondaryContainer = Color(0xFFF4BE48)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCE)
val md_theme_dark_tertiary = Color(0xFFBCD063)
val md_theme_dark_onTertiary = Color(0xFF2B3400)
val md_theme_dark_tertiaryContainer = Color(0xFF404C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFD8EC7B)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFFF4BE48)
val md_theme_dark_onError = Color(0xFFF4BE48)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFFF4BE48)
val md_theme_dark_onBackground = Color(0xFFFFD9E4)
val md_theme_dark_surface = Color(0xFFF4BE48)
val md_theme_dark_onSurface = Color(0xFFFFD9E4)
val md_theme_dark_surfaceVariant = Color(0xFF4D4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C5B4)
val md_theme_dark_outline = Color(0xFF998F80)
val md_theme_dark_inverseOnSurface = Color(0xFFF4BE48)
val md_theme_dark_inverseSurface = Color(0xFFFFD9E4)
val md_theme_dark_inversePrimary = Color(0xFFF4BE48)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF4BE48)
val md_theme_dark_outlineVariant = Color(0xFF4D4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFD88C)